### ISSUE TITLE
When I trying to go to hideout, it's only put "av" in the local chat

### ISSUE THREAD

**Issue by gogunow** [redSol/PoeTradeSearchEN#6]
Also when I'm using F1, F4 too. 
Run as admin. F9-10 functions work fine

**Comment by redSol** [comment]
have you edited your config file? and if so, may you post it here

**Comment by gogunow** [comment]
I've not. The problem was in the previous release too, now I have downloaded the newest and the problem stayed. I didn't edit anything now

**Comment by redSol** [comment]
I've released another version, please try it out and let me know. Make sure you replace everything including the config file.

**Comment by gogunow** [comment]
Yep, it seems to work fine now. 
Thanks!

**Comment by gogunow** [comment]
Nah. The problem is still there. 
![screenshot-0015](https://user-images.githubusercontent.com/55152303/72186431-4f1d7480-3406-11ea-95fb-69f18085aaaa.png)

**Comment by redSol** [comment]
I've released another version, please try it out
